# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c065f88b0f83425306d9ba9ae8a0e13cc563bfeca29f1074b3194787e321f053d36436b9447160c1b83a94405c1354a3510b0aa2250e53b59514564680d20a2

test:
  secret_key_base: 897a925d7308f5af437bd47983c9085caeba4593302a215b6687a71432c9a01d0762543549933339c1abb50ca389607abb62f0fdc4ee634ef32e8d2151a29b23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
